### ISSUE TITLE
onnx模型中添加一个新的卷积层，可以做吗？

### ISSUE THREAD

**Issue by 394781865** [bindog/onnx-surgery#1]
我想在onnx模型中添加一个卷积层，用你的代码可以实现吗？

**Comment by bindog** [comment]
当然可以做，不过有些细节上的代码需要自己添加，我简单写了一个例子，可以参考最新的代码https://github.com/bindog/onnx-surgery/commit/cd7e2201fad6d15af600d67f89266b256c4b952f

添加的卷积层的属性和权重(用numpy即可，注意shape)都要自己设定，命名规范参考这个[文档](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv)，而且需要自己保证前后input和output的shape一致性，否则会在inference的时候报错

不过你为什么需要在ONNX中添加一个卷积层呢？按理说ONNX已经到了部署阶段，只适用一些不涉及到权重的修改，而卷积层里包含了需要训练才能得到的权重，你直接添加能保证结果正确吗？

**Comment by 394781865** [comment]
十分感谢信你的回信和帮助！我是一名算法落地工程师，最近需要实现一个功能（某某资深落地工程师的要求），即往训练好的onnx模型中添加一个卷积层。具体什么时候用、怎么去用，我也不清楚。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bindog"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 中午11:54
收件人:&nbsp;"bindog/onnx-surgery"<onnx-surgery@noreply.github.com&gt;;
抄送:&nbsp;"光风霁月"<394781865@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bindog/onnx-surgery] onnx模型中添加一个新的卷积层，可以做吗？ (#1)





 
当然可以做，不过有些细节上的代码需要自己添加，我简单写了一个例子，可以参考最新的代码cd7e220
 
添加的卷积层的属性和权重(用numpy即可，注意shape)都要自己设定，命名规范参考这个文档，而且需要自己保证前后input和output的shape一致性，否则会在inference的时候报错
 
不过你为什么需要在ONNX中添加一个卷积层呢？按理说ONNX已经到了部署阶段，只适用一些不涉及到权重的修改，而卷积层里包含了需要训练才能得到的权重，你直接添加能保证结果正确吗？
