### ISSUE TITLE
onnx添加新的层之后会出现问题

### ISSUE THREAD

**Issue by 205418367** [bindog/onnx-surgery#2]
你好！我在onnx模型中添加了新的层，比如softmax等。但是onnx.checker.check_model(self.model)会出错，如何解决呢？因为我还需要把onnx模型转MNN、NCNN等模型，必须要check_model。

**Comment by bindog** [comment]
我之前已经注意到了这个问题，但是因为不影响onnxruntime的inference就没管了……刚才看了下onnx的源码，它对node的拓扑顺序是有要求的：被依赖的前驱节点必须要出现在后继节点的前面。而我在实现的时候用的是append，即添加到最末端，所以会报错，现已修复，你测试一下看还有问题么？

**Comment by 205418367** [comment]
好的，有时间我测试一下
