### ISSUE TITLE
onnx添加而外输出后check的时候报错

### ISSUE THREAD

**Issue by steelbin** [bindog/onnx-surgery#3]
使用来自onnx提供的预训练模型“mobilenetv2-7.onnx”，下载链接：https://github.com/onnx/models/blob/master/vision/classification/mobilenet/model/mobilenetv2-7.onnx

测试脚本：工程中的example.py

```
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="onnx test")
    parser.add_argument("--input", default="", type=str, required=True)
    parser.add_argument("--output", default="", type=str, required=True)
    args = parser.parse_args()
    onnxsu = Surgery(args.input)
    # old_mxnet_version_example(onnxsu)
    # tf_set_batch_size_example(onnxsu, 16)
    debug_internal_output(onnxsu, "mobilenetv20_features_linearbottleneck0_conv0_fwd", "debug_test")
    # tensorrt_set_epsilon_example(onnxsu, 1e-3)
    # add_conv_layer(onnxsu, "resnetv24_batchnorm1_fwd")
    onnxsu.export(args.output)
```

错误信息：
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'type' of value_info is required but missing.

**Comment by bindog** [comment]
我用你说的文件测试了一下，应该是ONNX IR的版本更新了？对value_info的要求更高了，创建时还额外需要指定type和shape了，但是有些onnx文件是没有带shape信息的，所以我在加载模型的时候先做了shape_inference，然后再根据这些信息来创建value_info，现在应该可以了，你可以再尝试一下

**Comment by steelbin** [comment]
谢谢，我测试了，没有报错了。
