### ISSUE TITLE
如何Resize一个onnx模型输入节点的尺寸大小

### ISSUE THREAD

**Issue by kong869** [bindog/onnx-surgery#4]
您好，我遇到一个修改onnx模型输入尺寸大小的问题，我尝试了直接修改dim_value的值是不可以的（会导致推理结果位置改变），使用`set_model_input_shape`和Resize是等同的效果吗？如果不是，您有什么好的建议？

**Comment by bindog** [comment]
set_model_input_shape的主要用途还是修改batch_size的维度，如果直接修改c,h,w这几个维度是有问题的，因为会与网络后面的参数无法匹配

正常的做法应该是在将输入送到onnx之前就做好resize，而不是在onnx里面来做。当然如果一定要在onnx里面来做resize，可以考虑人工加入一个resize的operator，其属性值和参数的设定请参考https://github.com/onnx/onnx/blob/master/docs/Operators.md#resize

**Comment by kong869** [comment]
嗯嗯 正在按照这个方式解决，谢谢
